version: "3.5"
services:
  app:
    image: maven:3.6.3-jdk-11
    volumes:
      - ..:/usr/src/mymaven
    command: >
      sh -c "mvn clean install &&
             java -jar /usr/src/mymaven/target/java-implementation-1.0.jar"